name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
          CC: gcc
          CXX: g++
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo add-apt-repository universe -y
        sudo apt update -y
        sudo apt install -y cmake \
                            gcc \
                            g++ \
                            libgl1-mesa-dev \
                            qt6-base-dev \
                            qt6-l10n-tools \
                            qt6-tools-dev \
                            qt6-tools-dev-tools \
                            qt6-wayland-dev
    - name: Configure
      env:
        CC: ${{ matrix.CC }}
        CXX: ${{ matrix.CXX }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -S ${{ github.workspace }} -B build
    - name: Build
      run: |
        cmake --build build --parallel
